# FROM arm32v7/python:3.7-slim-buster
FROM balenalib/raspberry-pi-debian:latest

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && \
    apt-get install sense-hat && \
    apt-get install python3-dev libffi-dev libssl-dev && \
    apt-get install python3-pip && \
    pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]